Repository openshift/velero-plugin-for-microsoft-azure, pull requests merged in 2024-03, with the labels that each got.

#45 oadp-1.1: CVE-2023-44487 gRPC-Go HTTP/2 Rapid Reset vulnerability
  go.mod
  go.sum
Labels: approved, lgtm

#49 OADP-3586: Update to ubi9 builder and base images
  Dockerfile.ubi
Labels: approved, lgtm, jira/valid-reference

#44 oadp-1.2: CVE-2023-44487 gRPC-Go HTTP/2 Rapid Reset vulnerability
  go.mod
  go.sum
Labels: lifecycle/rotten, approved, lgtm

#50 [oadp-1.3] OADP-3657: fix CVE CVE-2024-24786
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference
